BADHABITS = [
"One, two, three, four",
"Ooh, ooh",
"Every time you come around, you know I can't say no",
"Every time the sun goes down, I let you take control",
"I can feel the paradise before my world implodes",
"And tonight had something wonderful",
"My bad habits lead to late nights, endin' alone",
"Conversations with a stranger I barely know",
"Swearin' this will be the last, but it probably won't",
"I got nothin' left to lose, or use, or do",
"My bad habits lead to wide eyes stare into space",
"And I know I'll lose control of the things that I say",
"Yeah, I was lookin' for a way out, now I can't escape",
"Nothin' happens after two, it's true, it's true",
"My bad habits lead to you",
"Ooh-ooh, ooh-ooh",
"My bad habits lead to you",
"Ooh-ooh, ooh-ooh",
"My bad habits lead to you",
"Every pure intention ends when the good times start",
"Fallin' over everything to reach the first time's spark",
"It started under neon lights and then it all got dark",
"I only know how to go too far",
"My bad habits lead to late nights, endin' alone",
"Conversations with a stranger I barely know",
"Swearin' this will be the last, but it probably won't",
"I got nothin' left to lose, or use, or do",
"My bad habits lead to wide eyes stare into space",
"And I know I'll lose control of the things that I say",
"Yeah, I was lookin' for a way out, now I can't escape",
"Nothin' happens after two, it's true, it's true",
"My bad habits lead to you",
"Ooh-ooh, ooh-ooh",
"My bad habits lead to you",
"Ooh-ooh, ooh-ooh",
"We took the long way 'round",
"Burned 'til the fun ran out, now",
"My bad habits lead to late nights, endin' alone",
"Conversations with a stranger I barely know",
"Swearin' this will be the last, but it probably won't",
"I got nothin' left to lose, or use, or do",
"My bad habits lead to wide eyes stare into space",
"And I know I'll lose control of the things that I say",
"Yeah, I was lookin' for a way out, now I can't escape",
"Nothin' happens after two, it's true, it's true",
"My bad habits lead to you",
"Ooh-ooh, ooh-ooh",
"My bad habits lead to you",
"Ooh-ooh, ooh-ooh",
"My bad habits lead to you"
]